// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Answers struct {
	ID         int32     `json:"id"`
	UserID     int32     `json:"user_id"`
	QuestionID int32     `json:"question_id"`
	Texto      string    `json:"texto"`
	SessionID  int32     `json:"session_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Questions struct {
	ID        int32     `json:"id"`
	Texto     string    `json:"texto"`
	CreatedAt time.Time `json:"created_at"`
}

type SessionProgress struct {
	ID         int32        `json:"id"`
	SessionID  int32        `json:"session_id"`
	QuestionID int32        `json:"question_id"`
	IsAnswered bool         `json:"is_answered"`
	AnsweredAt sql.NullTime `json:"answered_at"`
}

type Sessions struct {
	ID                int32         `json:"id"`
	UserID            int32         `json:"user_id"`
	CurrentQuestionID sql.NullInt32 `json:"current_question_id"`
	StartedAt         time.Time     `json:"started_at"`
	CompletedAt       sql.NullTime  `json:"completed_at"`
}

type Users struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
